#import { PostPreview } from "../fragments.gql"

query getAllPosts($language: LanguageCodeFilterEnum) {
    posts(where: {language: $language}) {
        edges {
            ...PostPreview
        }
    }
}